[package]
name = "powerline"
version = "0.2.0"
authors = ["cirho <me@cirho.com>"]
edition = "2018"

[dependencies]
users = "0.9"
libc = "0.2"
hostname = "0.1.5"
git2 = { version = "0.10", optional = true, default-features = false}
chrono = "0.4"


[features]
default = ["zsh-shell", "libgit"]
bash-shell = []
bare-shell = []
zsh-shell = []
libgit = ["git2"]

[profile.release]
opt-level = 3
lto = true
debug = false
